
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: nicegui_frontend
    environment:
      - BACKEND_HOST=backend
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
