version: '3.8'

services:
  backend:
    build: ./backend
    container_name: gauss_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./fronted
    container_name: gauss_frontend
    ports:
      - "3000:3000"
      - "8001:8001"
    depends_on:
      - backend